[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/ctext/search"
  to = "/.netlify/functions/ctext-search"
  status = 200
  force = true

[[redirects]]
  from = "/transcriptions/tei_hanshu/1a.html"
  to = "/transcriptions/tei_hanshu/1a/"
  status = 301
  force = true

[[redirects]]
  from = "/transcriptions/tei_brhat/1r.html"
  to = "/transcriptions/tei_brhat/1r/"
  status = 301
  force = true
